

[module]
[module.hugoVersion]
min = "0.77.0"

baseURL = "http://www.rewardseasy.co.za/"
title = "Rewards Easy"
theme = "hugo-coder"
languagecode = "za"
defaultcontentlanguage = "za"

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
author = "Dylan Govender"

faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"

since = 2023

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

# customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]

[taxonomies]
category = "categories"

# Social links
#[[params.social]]
#name = "Github"
#icon = "fa fa-github fa-2x"
#weight = 1
#url = "https://github.com/johndoe/"
#[[params.social]]
#name = "Gitlab"
#icon = "fa fa-gitlab fa-2x"
#weight = 2
#url = "https://gitlab.com/johndoe/"
#[[params.social]]
#name = "Twitter"
#icon = "fa fa-twitter fa-2x"
#weight = 3
#url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url  = "posts/"
[[menu.main]]
name = "About"
weight = 2
url = "about/"
